### ISSUE TITLE
Apple Watch support

### ISSUE THREAD

**Issue by bns34** [j4nf4b3l/MagicCFG#2]
I'm guessing this doesn't support Apple Watch because that's what MagicClock is for. How am I able to get MagicClock

**Comment by IamJoker03** [comment]
![Screenshot 2021-07-05 at 1 35 26 AM](https://user-images.githubusercontent.com/34206615/124398074-5be80380-dd31-11eb-9a9f-b4c7275844b2.png)
iPhone 7 Stuck on adding NvSn, Any help appreciated :)

**Comment by j4nf4b3l** [comment]
> I'm guessing this doesn't support Apple Watch because that's what MagicClock is for. How am I able to get MagicClock

There's currently no ETA for MagicClock and no way to get a copy for it.
But there are plans, patience is the key ☺️
